name: your_app_name
description: A new Flutter project.

publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Adjust according to your Dart SDK version
  
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0  # Use the latest version
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^2.0.0  # Use the latest version

flutter:
  uses-material-design: true
